spring.application.name=medconsult

spring.datasource.url=jdbc:mysql://localhost:3306/medconsult_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=akshai
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.address=0.0.0.0
server.port=8080

#jwt
jwt.secret=sq08Y/YLDzzh5Jdu5P/PIddWbf0udms0YfmnrXaKlBRqn3pOBr3K5nZe16hw+QgdZreUiUVnAb9SHEbbkcT1fw==
jwt.expiration=86400000


# Dialect
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JSON support (optional if using Hibernate Types)
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
